linters:
  disable:
    - exhaustivestruct
    - gochecknoglobals
    - exhaustruct
    - varnamelen

    # deprecated
    - scopelint
    - maligned
    - golint
    - interfacer
  presets:
    - bugs
    # - comment
    - unused
    - complexity
    - error
    - format
    - import
    # - metalinter
    - module
    - performance
    # - sql
    - style
    - test

linters-settings:
  stylecheck:
    checks: ["all", "-ST1005"]
